### ISSUE TITLE
Nav bar best Practices peer code review 

### ISSUE THREAD

**Issue by Abbas-Aljuaifari** [tchasinga/Final-capstone-module-one#2]
When creating a navigation bar (navbar) in HTML, there are several best practices to follow to ensure a clean and accessible design. Here are some recommended best practices for creating an HTML navbar:

Use semantic HTML elements: Use appropriate semantic HTML elements to structure your navbar. The <nav> element should wrap the entire navbar, and ` <ul> ` and ` <li>` elements should be used to create the list of navigation items.
html
code example
```
<nav>
  <ul>
    <li><a href="#">Home</a></li>
    <li><a href="#">About</a></li>
    <li><a href="#">Services</a></li>
    <li><a href="#">Contact</a></li>
  </ul>
</nav>
```
Provide clear and concise labels: Use descriptive labels for each navigation item to help users understand the purpose of each link. Avoid using vague or ambiguous labels.
Use meaningful link text: Ensure that the link text within each <a> element accurately represents the destination or action it performs. Avoid using generic phrases like "click here" or "read more."
Make it responsive: Implement responsive design techniques to ensure that your navbar adapts well to different screen sizes and devices. Consider using CSS media queries and techniques like flexbox or grid to create a responsive navbar that collapses into a hamburger menu or expands based on available space.
Add accessibility features: Make your navbar accessible by providing proper attributes, such as aria-label, aria-expanded, and aria-haspopup, to indicate the purpose and state of the navigation elements. Ensure that keyboard navigation is supported, and consider adding skip navigation links for better accessibility.
Style with CSS: Use CSS to style your navbar according to your design requirements. Apply appropriate colors, typography, spacing, and hover effects to enhance the visual appearance and usability of the navigation bar. Consider using CSS frameworks like Bootstrap or Tailwind CSS for ready-made navbar styles and responsive capabilities.
Test across browsers and devices: Ensure that your navbar works well across different browsers and devices by performing thorough testing. Verify that the navbar layout, functionality, and responsiveness are consistent and functional on various screen sizes and browser environments.
Keep it lightweight: Avoid adding unnecessary elements or excessive JavaScript functionality to your navbar, as it can increase page load time and negatively impact user experience. Keep your HTML markup and CSS code clean and minimal for optimal performance.
By following these best practices, you can create a well-structured, accessible, and visually appealing navbar in your HTML web pages. Remember to adjust and customize the design and behavior of your navbar to align with your specific project requirements and brand guidelines.

**Comment by melkamu12** [comment]
I respectfully suggest that, it is not good to write different semantics by separating for mobile and desktop version in HTML. This is because it can lead to a number of problems, including:

Increased development time and cost: It takes more time and money to develop two separate versions of a website, as you need to design, develop, and test each version separately.

Reduced performance: Serving two separate versions of a website can reduce performance, as the browser needs to download and render two sets of HTML, CSS, and JavaScript files.

Duplicated content: If you have two separate versions of a website, you may end up with duplicated content, which can lead to SEO penalties.

Poor user experience: Users may have a poor experience if they switch between the mobile and desktop versions of a website, as the layout and design may not be consistent.

 I wonder if do with one semantices for footer and header.
